version: '3.8'

services:
    db-postgres:
      image: postgres:latest
      environment:
        POSTGRES_DB: wb
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: 12345
      ports: 
        - "5433:5432"
      volumes: 
        - db_data:/var/lib/postgresql/data
        #- ./sql/create.sql:/docker-entrypoint-initdb.d/init.sql
        - ./migr.sh:/docker-entrypoint-initdb.d/init.sh
        - ./backup.sql:/docker-entrypoint-initdb.d/init.sql
    nats:
      image: "nats:latest"
      entrypoint: /nats-server
      command: "-js"
      ports:
        - "4222:4222"
volumes:
  db_data:
networks:
  default: